version: 2
updates:
- package-ecosystem: maven
  target-branch: "develop"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: maven
  target-branch: "charphi-patch-1"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
