import:
  - java_base.yml
  - java_linux_arm64.yml
  - java_windows_amd64.yml
  - maven_snapshots_from_develop.yml
  - maven_releases_from_tags.yml

jobs:
  include:
    - name: "linux-amd64-openjdk8"
      jdk: openjdk8
      os: linux

    - name: "linux-amd64-openjdk11"
      jdk: openjdk11
      os: linux

    - name: "linux-amd64-openjdk-ea"
      jdk: openjdk-ea
      os: linux

    - name: "linux-arm64-openjdk11"
      jdk: openjdk11
      <<: *_java_linux_arm64

    - name: "macos-amd64-openjdk11"
      jdk: openjdk11
      os: osx

    - name: "windows-amd64-openjdk11"
      env: TRAVIS_JDK_VERSION=openjdk11
      <<: *_java_windows_amd64

  allow_failures:
    - jdk: openjdk-ea
