name: Check changelog

on: [ push, pull_request ]

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-changelog-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.21.0

      - name: Check changelog using Heylogs latest version
        uses: jbangdev/jbang-action@v0.141.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.18.0:bin
          scriptargs: "check -f github-actions"
