name: Documentation on GitHub pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    env:
      THEME_VERSION: v0.32.3
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Download theme
        run: |
          mkdir -p docs/themes/hugo-geekdoc/
          curl -sSL "https://github.com/thegeeklab/hugo-geekdoc/releases/download/${{THEME_VERSION}}/hugo-geekdoc.tar.gz" | tar -xz -C docs/themes/hugo-geekdoc/ --strip-components=1

      - name: Build
        run: hugo --source docs -b http://nbbrd.github.io/sandbox/docs/develop

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          destination_dir: ./docs/develop
