name: Heylogs badge

on: [ push ]

jobs:
  update-changelogs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Scan changelog
        run: |
          mkdir heylogs
          mvn dependency:copy -Dartifact=com.github.nbbrd.heylogs:heylogs-cli:0.8.0:jar:bin -DoutputDirectory=. -Dmdep.stripVersion -q
          java -jar heylogs-cli-bin.jar scan -f json -o heylogs/scan.json

      - name: Deploy scan summary
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./heylogs
          destination_dir: ./heylogs
