name: sdmx-dl example

on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-

      - name: Print latest stable version of sdmx-dl
        uses: jbangdev/jbang-action@v0.81.2
        with:
          script: sdmx-dl@nbbrd
          scriptargs: "--version"
        env:
          JBANG_REPO: /root/.jbang/repository
