name: JBang example

on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    name: heylogs version
    steps:
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-

      - name: Print latest stable version of heylogs using catalog
        uses: jbangdev/jbang-action@v0.115.0
        with:
          trust: https://github.com/nbbrd/jbang-catalog/
          script: heylogs@nbbrd
          scriptargs: "--version"
        env:
          JBANG_REPO: ~/.jbang/repository

      - name: Print latest stable version of sdmx-dl using Maven coordinate
        uses: jbangdev/jbang-action@v0.115.0
        with:
          script: com.github.nbbrd.sdmx-dl:sdmx-dl-cli:RELEASE:bin
          scriptargs: "--version"
        env:
          JBANG_REPO: ~/.jbang/repository
