name: Update GitHub dependency

on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    name: Update GitHub dependency

    env:
      DEP_REPO: thegeeklab/hugo-geekdoc
      DEP_PROP: hugo-geekdoc.version

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Check for update
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ env.DEP_REPO }}

      - name: Apply update on Maven POM
        run: >
          mvn -B -ntp versions:set-property 
          -Dproperty=${{ env.DEP_PROP }}
          -DnewVersion=${{ steps.latest-release.outputs.release }} 
          -DgenerateBackupPoms=false

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Bump ${{ env.DEP_PROP }} from xxx to ${{ steps.latest-release.outputs.release }}
          title: Bump ${{ env.DEP_PROP }} from xxx to ${{ steps.latest-release.outputs.release }}
          body: ${{ steps.latest-release.outputs.description }}
          delete-branch: true

      - name: Create summary
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
