name: Update resource

on: workflow_dispatch

jobs:
  run-job:
    runs-on: ubuntu-latest
    name: Update resource

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Check for updates
        id: geekdoc
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: thegeeklab/hugo-geekdoc

      - name: Apply update on Maven POM
        run: >
          mvn -B -ntp versions:set-property 
          -Dproperty=hugo-geekdoc.version 
          -DnewVersion=${{ steps.geekdoc.outputs.release }} 
          -DgenerateBackupPoms=false

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Bump hugo-geekdoc from xxx to ${{ steps.geekdoc.outputs.release }}
          title: Bump hugo-geekdoc from xxx to ${{ steps.geekdoc.outputs.release }}
          body: ${{ steps.geekdoc.outputs.description }}
          delete-branch: true

      - name: Create summary
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
