name: Test compatibility

on: workflow_dispatch

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-changelog-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.19.0

      - name: Check compatibility
        run: |
          mvn com.github.nbbrd.nbbrd-maven-tools:compatibility-maven-plugin::check-downstream \
            -D "compatibility.source=https://github.com/jdemetra/jdplus-main" \
            -D "compatibility.sourceBinding=eu.europa.ec.joinup.sat:jdplus*" \
            -D "compatibility.sourceRef=v3.7.1" \
            -D "compatibility.targets=https://github.com/nbbrd/jdplus-sdmx,https://github.com/jdemetra/jdplus-nowcasting" \
            -D "compatibility.targetLimits=1,1" \
            -D "compatibility.logErrors=true" \
            -D "compatibility.reportFile=./compatibility/report.md"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./compatibility
          destination_dir: ./compatibility
