name: Generate heylogs CLI Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JBang
        uses: jbangdev/setup-jbang@main

      - name: Trust heylogs catalog
        run: jbang trust add https://github.com/nbbrd/

      - name: Create heylogs alias
        run: |
          jbang alias add --force heylogs@nbbrd

      - name: Install asciinema and expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect asciinema

      - name: Create demo directory
        run: mkdir -p docs

      - name: Run demo recording
        run: bash scripts/generate-heylogs-demo.sh

      - name: ⬆️ Upload demo
        uses: actions/upload-artifact@v7
        with:
          path: |
            docs/demo.cast
            scripts/generate-heylogs-demo.sh
